comment:
  layout: "reach, diff, flags, files"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 3%
    patch:
      default:
        target: 70%
        threshold: 3%